spring.application.name=appointment-service
server.port=8082

# Database Configuration
spring.datasource.url=${APPOINTMENT_DB_URL:jdbc:postgresql://localhost:5438/appointment_db}
spring.datasource.username=${DB_USER:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Kafka Properties
spring.kafka.bootstrap-servers=${SPRING_KAFKA_BOOTSTRAP_SERVERS:localhost:9092}
spring.kafka.consumer.group-id=appointment-service-group
spring.kafka.consumer.auto-offset-reset=earliest
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.apache.kafka.common.serialization.ByteArraySerializer

# gRPC Client Settings
patient.grpc.host=${PATIENT_GRPC_HOST:localhost}
patient.grpc.port=${PATIENT_GRPC_PORT:9005}
doctor.grpc.host=${DOCTOR_GRPC_HOST:localhost}
doctor.grpc.port=${DOCTOR_GRPC_PORT:9002}
server.error.include-message=always
